[tool.poetry]
name = "suppi"
version = "0.1.0"
description = ""
authors = ["Andrei Kulakov <kulakov1@tut.by>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
